### ISSUE TITLE
Bot Error

### ISSUE THREAD

**Issue by Ansat527** [AleXwern/FFXIV-Encounter-Compiler#1]
Hey, I'm getting an error 403 whenever I post a link for the report from the bot, I saw the other error comments, but couldn't find any mention of a 403 error

**Comment by Ansat527** [comment]
Solved, error 403 was solved by adding a name to the FFLogs V1 key

**Comment by AleXwern** [comment]
For future reference for anyone who comes across this:
401 means the API key is invalid or doesn't exist
403 means the API key is valid but the "bot" is not named on FFlogs side. You need to name the V1 client on your FFlogs user settings in order to access the API.
![beta](https://user-images.githubusercontent.com/56729063/123560483-106eac00-d7ab-11eb-8647-7abcedfcac88.png)
Refer to README which will be updated soonish.
